import './globals.css'
import type { Metadata } from 'next'
import { Fira_Code } from 'next/font/google'

const fira = Fira_Code({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '3Dw0rld',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={fira.className}>{children}</body>
    </html>
  )
}
